In [6]:
num = [1, 2, 3, 4, 5]
new_list = [x * 2 for x in num]

print(new_list)


[2, 4, 6, 8, 10]


In [7]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])
new_array = numbers * 2

print(new_array)


[ 2  4  6  8 10]


In [8]:
lst = [[2,3,4,5,6],[2,4,5,6,6]]
print(lst[0][4])


6


In [9]:
import numpy as np
lst = [[[2, 3, 4, 5, 6], [2, 4, 5, 6, 6]]]
arr = np.array(lst)
print(arr.ndim)



3


In [10]:
import numpy as np

numbers = np.array([[1, 2, 3, 4, 5]])
new_array = numbers.ndim

print(new_array)

2


In [11]:
x = [[1,2,3,4],[2,3,4,5],[5,6,7,8]]
number = np.array(x)
number = number * 4 
print(number)

[[ 4  8 12 16]
 [ 8 12 16 20]
 [20 24 28 32]]


In [17]:
arr = np.array([1,2,3,4,5])
print(arr + 1 )
print(arr - 1 )
print(arr * 4 )
print(arr / 5 )
print(arr ** 2 )


[2 3 4 5 6]
[0 1 2 3 4]
[ 4  8 12 16 20]
[0.2 0.4 0.6 0.8 1. ]
[ 1  4  9 16 25]
