In [31]:
num = [1, 2, 3, 4, 5]
new_list = [x * 2 for x in num]

print(new_list)


[2, 4, 6, 8, 10]


In [32]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])
new_array = numbers * 2

print(new_array)


[ 2  4  6  8 10]


In [33]:
lst = [[2,3,4,5,6],[2,4,5,6,6]]
print(lst[0][4])


6


In [34]:
import numpy as np
lst = [[[2, 3, 4, 5, 6], [2, 4, 5, 6, 6]]]
arr = np.array(lst)
print(arr.ndim)



3


In [35]:
import numpy as np

numbers = np.array([[1, 2, 3, 4, 5]])
new_array = numbers.ndim

print(new_array)

2


In [36]:
x = [[1,2,3,4],[2,3,4,5],[5,6,7,8]]
number = np.array(x)
number = number * 4 
print(number)

[[ 4  8 12 16]
 [ 8 12 16 20]
 [20 24 28 32]]


In [37]:
arr = np.array([1,2,3,4,5])
print(arr + 1 )
print(arr - 1 )
print(arr * 4 )
print(arr / 5 )
print(arr ** 2 )


[2 3 4 5 6]
[0 1 2 3 4]
[ 4  8 12 16 20]
[0.2 0.4 0.6 0.8 1. ]
[ 1  4  9 16 25]


In [38]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([2, 3.4, 4, 5.7, 6, 7.2])
print(np.square(arr))
print(np.round(arr2))
print(np.floor(arr2))


[ 1  4  9 16 25]
[2. 3. 4. 6. 6. 7.]
[2. 3. 4. 5. 6. 7.]


In [39]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([2, 3, 4, 5, 6, 7])
print(arr1 ** arr2)

[     1      8     81   1024  15625 279936]


In [40]:
import numpy as np
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[2, 3, 4],[5, 6, 7]])
print(arr1 * arr2)

[[ 2  6 12]
 [20 30 42]]


In [41]:
a= np.array([20,30,40,50,60,77,435,222])
print(a==60)
print(a>100)
print(a[a==60])
a[ a<100 ]=0

print(a)

[False False False False  True False False False]
[False False False False False False  True  True]
[60]
[  0   0   0   0   0   0 435 222]
